import { NextRequest } from 'next/server'

interface EmailReportRequest {
  recipientEmail: string
  recipientName: string
  reportContent: string
  reportData: any
  locale?: 'en' | 'es'
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json() as EmailReportRequest
    const { recipientEmail, recipientName, reportContent, reportData, locale = 'en' } = body

    if (!recipientEmail || !reportContent) {
      return new Response(
        JSON.stringify({ error: 'Email and report content are required' }),
        {
          status: 400,
          headers: { 'Content-Type': 'application/json' }
        }
      )
    }

    // For now, we'll use mailto: link functionality since email services require API keys
    // In production, you would integrate with services like SendGrid, Mailgun, or AWS SES

    // Create a formatted email body
    const emailSubject = locale === 'en'
      ? `Your Personalized Home Buying Plan - CasaReady`
      : `Tu Plan Personalizado de Compra de Casa - CasaReady`

    const emailBody = `
${locale === 'en' ? 'Hello' : 'Hola'} ${recipientName},

${locale === 'en'
  ? 'Thank you for using our Home Buying Wizard! Here is your personalized home buying plan:'
  : 'Gracias por usar nuestro Asistente de Compra de Casa! Aquí está tu plan personalizado de compra de casa:'
}

${locale === 'en' ? 'AFFORDABILITY ANALYSIS:' : 'ANÁLISIS DE CAPACIDAD DE PAGO:'}
${locale === 'en' ? '• Recommended Price Range:' : '• Rango de Precio Recomendado:'} $${reportData.estimatedPrice?.toLocaleString()}
${locale === 'en' ? '• Maximum Affordable:' : '• Máximo Asequible:'} $${reportData.maxAffordable?.toLocaleString()}
${locale === 'en' ? '• Estimated Monthly Payment:' : '• Pago Mensual Estimado:'} $${reportData.monthlyPayment?.toLocaleString()}

${locale === 'en' ? 'RECOMMENDED LOAN PROGRAMS:' : 'PROGRAMAS DE PRÉSTAMO RECOMENDADOS:'}
${reportData.programFit?.map((program: string, index: number) => `${index + 1}. ${program}`).join('\n')}

${locale === 'en' ? 'YOUR ACTION PLAN:' : 'TU PLAN DE ACCIÓN:'}
${reportData.actionPlan?.map((action: string, index: number) => `${index + 1}. ${action}`).join('\n')}

${locale === 'en' ? 'EXPERT TIPS:' : 'CONSEJOS DE EXPERTOS:'}
${reportData.tips?.map((tip: string, index: number) => `• ${tip}`).join('\n')}

---

${locale === 'en'
  ? 'Ready to take the next step? Contact Sully Ruiz Real Estate:'
  : '¿Listo para dar el siguiente paso? Contacta a Sully Ruiz Real Estate:'
}

📞 ${locale === 'en' ? 'Call/Text:' : 'Llamar/Mensaje:'} (512) 412-2352
📧 ${locale === 'en' ? 'Email:' : 'Correo:'} realtor@sullyruiz.com

${locale === 'en'
  ? 'Sully Ruiz, REALTOR® - Licensed in Texas\nKeller Williams Austin NW\nSpecializing in first-time buyers, ITIN clients, and bilingual service.'
  : 'Sully Ruiz, REALTOR® - Licenciado en Texas\nKeller Williams Austin NW\nEspecializado en compradores primerizos, clientes ITIN, y servicio bilingüe.'
}

---
${locale === 'en' ? 'Generated by CasaReady Home Buying Wizard' : 'Generado por el Asistente de Compra de Casa CasaReady'}
    `.trim()

    // Return mailto link that can be used on frontend
    const mailtoLink = `mailto:${recipientEmail}?subject=${encodeURIComponent(emailSubject)}&body=${encodeURIComponent(emailBody)}`

    return new Response(
      JSON.stringify({
        success: true,
        mailtoLink,
        message: locale === 'en'
          ? 'Email prepared successfully. Check your email client.'
          : 'Correo preparado exitosamente. Revisa tu cliente de correo.'
      }),
      {
        status: 200,
        headers: { 'Content-Type': 'application/json' }
      }
    )

  } catch (error) {
    console.error('Email report error:', error)

    return new Response(
      JSON.stringify({
        error: error instanceof Error ? error.message : 'Unknown error',
        timestamp: new Date().toISOString()
      }),
      {
        status: 500,
        headers: { 'Content-Type': 'application/json' }
      }
    )
  }
}